name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: CI=false npm run build

      - name: Set git user for deploy commit
        run: |
          git config --global user.name "Tejas"
          git config --global user.email "tejaskandri28@gmail.com"

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

